/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ConexionBasesdeDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JFPrincipalEmpleado extends javax.swing.JFrame {
ConexionBasesdeDatos conexion;
    /**
     * Creates new form NewMDIApplication
     */
private int idempledo;
    public JFPrincipalEmpleado(ConexionBasesdeDatos conexion,int idempledo) {
        initComponents();
        this.idempledo=idempledo;
        this.conexion=conexion;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpescritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpescritorio.setBackground(new java.awt.Color(86, 146, 60));

        JPEscritorio.setBackground(new java.awt.Color(86, 146, 60));
        JPEscritorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        JPEscritorio.setToolTipText("");

        javax.swing.GroupLayout JPEscritorioLayout = new javax.swing.GroupLayout(JPEscritorio);
        JPEscritorio.setLayout(JPEscritorioLayout);
        JPEscritorioLayout.setHorizontalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1648, Short.MAX_VALUE)
        );
        JPEscritorioLayout.setVerticalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        dpescritorio.add(JPEscritorio);
        JPEscritorio.setBounds(0, 0, 1650, 900);

        fmventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Accounting-icon.png"))); // NOI18N
        fmventa.setMnemonic('f');
        fmventa.setText("Venta");
        fmventa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/product-sales-report-icon.png"))); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Facturar");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fmventa.add(openMenuItem);

        menuBar.add(fmventa);

        mproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/product-icon.png"))); // NOI18N
        mproducto.setMnemonic('e');
        mproducto.setText("Producto");
        mproducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2-Utilities-icon.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Modificar");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        mproducto.add(cutMenuItem);

        menuBar.add(mproducto);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Register-icon.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Finalizar");
        helpMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jcMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcMenu.setSelected(true);
        jcMenu.setText("Cerrar Caja");
        jcMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cash-register-icon.png"))); // NOI18N
        jcMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMenuActionPerformed(evt);
            }
        });
        helpMenu.add(jcMenu);

        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        jMenu1.setText("Salir");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete-icon.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

JFPrincipalEmpleadoVentaFacturar ventana=new JFPrincipalEmpleadoVentaFacturar(conexion,idempledo);
dpescritorio.add(ventana);
   ventana.show();
// TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         
       if(JOptionPane.showConfirmDialog(this, "ESTA SEGURO DE CERRAR SESION")==0){
       JFcerrarSesionn ventana=new JFcerrarSesionn();
       ventana.show();
       this.dispose();
        }
        
        
              // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jcMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMenuActionPerformed

        
        if(jcMenu.getState()==false){
            fmventa.setEnabled(false);
       
       
        jcMenu.setEnabled(false);
        
        
        }       







// TODO add your handling code here:
    }//GEN-LAST:event_jcMenuActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
       
        JFPrincipalEmpleadoProductoModificar ventana=new JFPrincipalEmpleadoProductoModificar(conexion);
dpescritorio.add(ventana);
   ventana.show();

// TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JPanel JPEscritorio = new javax.swing.JPanel();
    public final javax.swing.JMenuItem cutMenuItem = new javax.swing.JMenuItem();
    public static javax.swing.JDesktopPane dpescritorio;
    public final javax.swing.JMenu fmventa = new javax.swing.JMenu();
    public final javax.swing.JMenu helpMenu = new javax.swing.JMenu();
    public final javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
    public final javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
    public final javax.swing.JCheckBoxMenuItem jcMenu = new javax.swing.JCheckBoxMenuItem();
    public final javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
    public final javax.swing.JMenu mproducto = new javax.swing.JMenu();
    public final javax.swing.JMenuItem openMenuItem = new javax.swing.JMenuItem();
    // End of variables declaration//GEN-END:variables

}
