/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ConexionBasesdeDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JFPrincipalAdministradorEmpleadosAñadir extends javax.swing.JInternalFrame {
ConexionBasesdeDatos conexion;
    /**
     * Creates new form JFPrincipalAdministradorEmpleadosAñadir
     */
    public JFPrincipalAdministradorEmpleadosAñadir(ConexionBasesdeDatos conexion) {
        initComponents();
        this.closable=true;
        this.iconable=true;
        this.conexion=conexion;
        try{
          txtid.setText(conexion.consultarmaximo("PERSONA", "pers_id") + "");
        }catch(Exception e){
                  
                  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtapellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbmasculino = new javax.swing.JRadioButton();
        rbfemenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        DCFecha = new datechooser.beans.DateChooserCombo();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.activeCaption);
        setTitle("Añadir Empleados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-list-add-user-icon.png"))); // NOI18N

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Identificacion");
        jLabel1.setName("Añadir Empleados"); // NOI18N

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(242, 242, 242));
        txtid.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtid.setText("4");
        txtid.setName("Añadir Empleados"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setText("Nombre(s)");
        jLabel2.setName("Añadir Empleados"); // NOI18N

        txtnombre.setBackground(new java.awt.Color(242, 242, 242));
        txtnombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtnombre.setName("Añadir Empleados"); // NOI18N

        txtapellido1.setBackground(new java.awt.Color(242, 242, 242));
        txtapellido1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtapellido1.setName("Añadir Empleados"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Apellidos");
        jLabel3.setName("Añadir Empleados"); // NOI18N

        txtapellido2.setBackground(new java.awt.Color(242, 242, 242));
        txtapellido2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtapellido2.setName("Añadir Empleados"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Genero");
        jLabel4.setName("Añadir Empleados"); // NOI18N

        rbmasculino.setBackground(java.awt.SystemColor.activeCaption);
        buttonGroup1.add(rbmasculino);
        rbmasculino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rbmasculino.setText("Masculino");
        rbmasculino.setName("Añadir Empleados"); // NOI18N

        rbfemenino.setBackground(java.awt.SystemColor.activeCaption);
        buttonGroup1.add(rbfemenino);
        rbfemenino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rbfemenino.setText("Femenino");
        rbfemenino.setName("Añadir Empleados"); // NOI18N
        rbfemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemeninoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Cedula");
        jLabel9.setName("Añadir Empleados"); // NOI18N

        txtcedula.setBackground(new java.awt.Color(242, 242, 242));
        txtcedula.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtcedula.setName("Añadir Empleados"); // NOI18N

        DCFecha.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    DCFecha.setFormat(2);
    try {
        DCFecha.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2014, 4, 3),
            new java.util.GregorianCalendar(2014, 4, 3))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    DCFecha.setFieldFont(new java.awt.Font("Century Gothic", java.awt.Font.PLAIN, 11));

    jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel10.setText("Fecha de Ingreso");
    jLabel10.setName("Añadir Empleados"); // NOI18N

    jButton1.setBackground(new java.awt.Color(242, 242, 242));
    jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jButton1.setText("Ingresar");
    jButton1.setName("Añadir Empleados"); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel11.setText("Clave");
    jLabel11.setName("Añadir Empleados"); // NOI18N

    txtclave.setBackground(new java.awt.Color(242, 242, 242));
    txtclave.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    txtclave.setName("Añadir Empleados"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(DCFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbmasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbfemenino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addComponent(DCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbmasculino)
                    .addComponent(rbfemenino)
                    .addComponent(jLabel9)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
            .addGap(29, 29, 29)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemeninoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String id,nombre,apellido1,apellido2,genero="",fecha;
    long cedula;
    id=txtid.getText();
    cedula=Long.parseLong(txtcedula.getText());
    nombre=txtnombre.getText();
    apellido1=txtapellido1.getText();
    apellido2=txtapellido2.getText();
    if(rbmasculino.isSelected()){
        genero="M";
    }
    if(rbfemenino.isSelected()){
        genero="F";
    }
    fecha=DCFecha.getText();
       try{
   conexion.insertar("PERSONA","pers_id,pers_cedula,pers_nombre,pers_apellido1,pers_apellido2,pers_genero,pers_fecha,pers_clave,tipo_id", ""+
                               id+","+cedula+",'"+nombre+"','"+apellido1+"','"+apellido2+"','"+genero+"','"+fecha+"','"+txtclave.getText()+"',3");
              JOptionPane.showMessageDialog(this, "Registro exitoso");
              txtid.setText((Integer.parseInt(txtid.getText())+1)+"");
              txtnombre.setText("");
              txtapellido1.setText("");
              txtapellido2.setText("");
              txtcedula.setText("");
              txtclave.setText("");
              rbfemenino.setSelected(false);
                            rbmasculino.setSelected(false);


       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error en la inserccion del registro");
       }
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DCFecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtapellido2;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
