/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConexionBasesdeDatos;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.net.URL;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class JFPrincipalEmpleadoVentaFacturar extends javax.swing.JInternalFrame {

    ConexionBasesdeDatos conexion;
    private int idempledo;
    Calendar calendario;
    int cantidadproducto;
    DefaultTableModel modelo;
    File archivo;
    FileWriter escribir;
    BufferedWriter ayudaescribir;
    PrintWriter imprimi;
    String fecha="";
    /**
     * Creates new form JFPrincipalEmpleadoVentaFacturar
     */
    public JFPrincipalEmpleadoVentaFacturar(ConexionBasesdeDatos conexion, int idempledo) {
        initComponents();
        this.closable=true;
        this.iconable=true;
        this.conexion = conexion;
        this.idempledo = idempledo;
        calendario = new GregorianCalendar();
        fecha = calendario.get(Calendar.DAY_OF_MONTH) + "/" + (calendario.get(Calendar.MONTH) + 1) + "/" + calendario.get(Calendar.YEAR);
        modelo = (DefaultTableModel) jtproducto.getModel();
        try {
            ResultSet info = conexion.consultarconcondicion("PERSONA", "pers_cedula,pers_nombre", "pers_id = " + idempledo);
            info.next();
            lblidempleado.setText(info.getString(1));
            lblnombreempleado.setText(info.getString(2));
            lblfecha.setText(fecha);
            lblfacturaid.setText(conexion.consultarmaximo("FACTURA", "fact_id") + "");
            File crearcarpetafecha=new File("C:\\Documentos Empresa\\FACTURAS\\"+fecha.replace("/","-"));
    crearcarpetafecha.mkdir();
        } catch (Exception e) {

        }
        
        String ruta="C:\\"+fecha.replace("/","-");
        File nuevacarpteta=new File(ruta);
        nuevacarpteta.mkdir();
        nuevacarpteta.exists();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnombreproducto = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbliva = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jscantidadproductos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtidproducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnombredelcliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblfacturaid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblnombreempleado = new javax.swing.JLabel();
        lblidempleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproducto = new javax.swing.JTable();

        setBackground(java.awt.SystemColor.activeCaption);
        setTitle("Factura Venta");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/product-sales-report-icon.png"))); // NOI18N

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        lblnombreproducto.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblnombreproducto.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        lbltotal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbltotal.setText("XXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel14.setText("TOTAL");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel12.setText("IVA 16%");

        lbliva.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbliva.setText("XXXXXXXXXXXXXXXXXXXXXXXX");

        lblsubtotal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblsubtotal.setText("XXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel9.setText("SUBTOTAL");

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setText("Finalizar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(221, 221, 221));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jscantidadproductos.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jscantidadproductos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jscantidadproductosStateChanged(evt);
            }
        });
        jscantidadproductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jscantidadproductosFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel8.setText("CANTIDAD");

        txtidproducto.setBackground(new java.awt.Color(221, 221, 221));
        txtidproducto.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtidproducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidproductoFocusLost(evt);
            }
        });
        txtidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproductoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setText("PRODUCTO ID");

        txtnombredelcliente.setBackground(new java.awt.Color(221, 221, 221));
        txtnombredelcliente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel6.setText("CLIENTE");

        lblfacturaid.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblfacturaid.setText("X");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("FACTURA N°");

        lblfecha.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblfecha.setText("XXXX/XX/XX");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel3.setText("FECHA:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel2.setText("NOMBRE EMPLEADO:");

        lblnombreempleado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblnombreempleado.setText("XXXXXXXXXXXXXXXXXXXXXXXXXXX");

        lblidempleado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblidempleado.setText("XXXXXX");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel1.setText("ID EMPLEADO:");

        jtproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Serial", "Nombre", "Valor Unitario", "Cantidad", "Subtotal", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductoMouseClicked(evt);
            }
        });
        jtproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtproductoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtproducto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbliva, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnombreproducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jscantidadproductos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblfacturaid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnombredelcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(40, 40, 40)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(lblidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblfacturaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfecha))
                    .addGap(13, 13, 13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtnombredelcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jscantidadproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(lblnombreproducto))
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblsubtotal))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(lbliva))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lbltotal))
                    .addGap(18, 18, 18)
                    .addComponent(jButton2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidproductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidproductoFocusLost
        try {
            if (!txtidproducto.getText().equals("")) {
                if (conexion.consultarexistencia("PRODUCTO", "prod_nombre", "prod_id", txtidproducto.getText().trim())) {

                } else {
                    JOptionPane.showMessageDialog(this, "El producto no existe");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo producto esta vacio");
            }

         try{
            if(conexion.consultarexistencia("PRODUCTO","prod_nombre", "prod_id","'"+ txtidproducto.getText().trim()+"'")){

                ResultSet info=conexion.consultarconcondicion("PRODUCTO","prod_nombre,prod_precio,prod_serial,prod_color,prod_modelo,prod_material", "prod_id = "+txtidproducto.getText()+"");
                info.next();

                lblnombreproducto.setText("NOMBRE DEL PRODUCTO: "+info.getString(1));
                
            }
            else{
               
                lblnombreproducto.setText("EL PRODUCTO NO EXISTE");
                
            }
        }catch(Exception e){

        }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_txtidproductoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//URL imgURL = getClass().getResource("C:\\Users\\Carlos\\Desktop\\x.png");


//ImageIcon imagen=new ImageIcon(imgURL);
      
        
        double subtotal=0.0,subtotal1=0.0;
        
        
        
        try {

            cantidadproducto = Integer.parseInt(jscantidadproductos.getValue().toString());
            if (cantidadproducto == 0) {
                JOptionPane.showMessageDialog(this, "La cantidad no puede ser  0");
            }
            if (cantidadproducto < 0) {
                JOptionPane.showMessageDialog(this, "La cantidad no puede ser menor  0");
            }

            int info1 = conexion.consultarsuma("INVENTARIO", "inve_cantidad", " WHERE prod_id= " + txtidproducto.getText(),1);

            int info2 = conexion.consultarsuma("VENTA", " DISTINCT  fact_id,venta_cantidad ", " WHERE prod_id= " + txtidproducto.getText(),2);
            System.out.println(info1+"OPERACION LOS QUE QUEDAN-->"+info2);
            int operacion = info1 - info2;
                       System.out.println("OPERACION -->"+operacion);

            ResultSet info3 = conexion.consultarconcondicion("PRODUCTO", "prod_serial,prod_nombre,prod_precio", "prod_id= " + txtidproducto.getText());
            info3.next();

            if (operacion == 0) {
                JOptionPane.showMessageDialog(this, "No existen mas productos en inventarios");
                
            } else {
                if (operacion <= cantidadproducto) {
                                   System.out.println("ENTRE 2");

                    JOptionPane.showMessageDialog(this, "Cantidad de productos seleccionados mayor a cantidad del prodcuto en almacen\n"
                            + "Se le colocara la cantidad total del los productos");
                    Object a[] = {txtidproducto.getText(), info3.getInt(1), info3.getString(2), info3.getString(3), operacion, Double.parseDouble(info3.getString(3)) * operacion,false};
                    modelo.addRow(a);
                    for(int i=0;i<modelo.getRowCount();i++){
                      subtotal=subtotal+Double.parseDouble(jtproducto.getValueAt(i,5).toString());         
                    }
                    lbltotal.setText(subtotal+"");
                    lbliva.setText((subtotal*0.16)+"");
                    lbltotal.setText((subtotal*0.16+subtotal)+"");
                    
                    for(int i=0;i<modelo.getRowCount();i++){
                      subtotal=subtotal+Double.parseDouble(jtproducto.getValueAt(i,5).toString());         
                    }
                    lblsubtotal.setText(subtotal+"");
                    lbliva.setText((subtotal*0.16)+"");
                    lbltotal.setText((subtotal*0.16+subtotal)+"");
                } else {
                    

                   // System.out.println(txtidproducto.getText()+"--"+ info3.getInt(1)+"--"+ info3.getString(2)+"--"+info3.getString(3)+"--"+ cantidadproducto+"--"+Double.parseDouble(info3.getString(3))*cantidadproducto +""+ cantidadproducto+"--"+"false");
                  //  subtotal1=Double.parseDouble(info3.getString(3));

subtotal1=info3.getDouble(3);
//System.out.println("valor1"+info3.getInt(1));
//System.out.println("valor2"+info3.getString(2));
Object a[] = {txtidproducto.getText(), info3.getString(1), info3.getString(2), info3.getString(3), cantidadproducto, (subtotal1*cantidadproducto),false};
System.out.println("HOLA");                    
modelo.addRow(a);
                    System.out.println("HOLA"+modelo.getRowCount());

                    for(int i=0;i<modelo.getRowCount();i++){
                      subtotal=subtotal+Double.parseDouble(jtproducto.getValueAt(i,5).toString());         
                    }
                    lblsubtotal.setText(subtotal+"");
                    lbliva.setText((subtotal*0.16)+"");
                    lbltotal.setText((subtotal*0.16+subtotal)+"");
                    
                    
                    
                    
                    
                }
            }
txtidproducto.setText("");
jscantidadproductos.setValue(1);
lblnombreproducto.setText("");
        } catch (Exception e) {

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jscantidadproductosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jscantidadproductosFocusLost


// TODO add your handling code here:
    }//GEN-LAST:event_jscantidadproductosFocusLost

    private void jscantidadproductosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jscantidadproductosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jscantidadproductosStateChanged

  
    
    
    private void jtproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductoMouseClicked
         double subtotal=0.0;
        int row = jtproducto.rowAtPoint(evt.getPoint());
        int col=jtproducto.columnAtPoint(evt.getPoint());
        if(col==4){
            int valoractual=(int)jtproducto.getValueAt(row, col);
            String a=JOptionPane.showInputDialog("Digite nueva cantidad");
            System.out.println("VALOR DE NUEVO-->"+a);
            if(a==null){
                
            }
            else{
                if(Integer.parseInt(a)<=0){
                    
                }
                else{
                  if(Integer.parseInt(a)>4){
                    
                } 
                  else{
                     
                      jtproducto.setValueAt(Integer.parseInt(a), row, col);
                      jtproducto.setValueAt((Integer.parseInt(a)*Double.parseDouble(jtproducto.getValueAt(row, col-1).toString())), row, col+1);
                      for(int i=0;i<modelo.getRowCount();i++){
                      subtotal=subtotal+Double.parseDouble(jtproducto.getValueAt(i,5).toString());         
                    }
                    lblsubtotal.setText(subtotal+"");
                    lbliva.setText((subtotal*0.16)+"");
                    lbltotal.setText((subtotal*0.16+subtotal)+"");
                    
                    
                  }
                }
            }
           
        }
        boolean eliminar=(boolean)jtproducto.getValueAt(row,6);
        
        if(eliminar==true){
           
            modelo.removeRow(row);
                        

            for(int i=0;i<modelo.getRowCount();i++){
                      subtotal=subtotal+Double.parseDouble(jtproducto.getValueAt(i,5).toString());         
                    }
                    lblsubtotal.setText(subtotal+"");
                    lbliva.setText((subtotal*0.16)+"");
                    lbltotal.setText((subtotal*0.16+subtotal)+"");
        }
        
        //System.out.println("MODELO-->FILA--> "+);        

// TODO add your handling code here:
    }//GEN-LAST:event_jtproductoMouseClicked

    private void jtproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtproductoKeyPressed

        


// TODO add your handling code here:
    }//GEN-LAST:event_jtproductoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        

try{
//PARTE DE BASES DE DATOS PARA INSERTAR--------------------------z
    
    
    conexion.insertar("FACTURA", "fact_id,fact_fecha,fact_cliente,fact_valor", lblfacturaid.getText()+",'"+fecha+"','"+txtnombredelcliente.getText()+"',"+lbltotal.getText());
    for(int i=0;i<jtproducto.getRowCount();i++ ){
                           for(int j=0;j<jtproducto.getColumnCount()-1;j++ ){
                            
                            
          ResultSet info=conexion.consultarconcondicion("PERSONA", "pers_id", "pers_cedula= "+lblidempleado.getText());
          info.next();
              
conexion.insertar("VENTA", "venta_cantidad,prod_id,pers_id,fact_id",jtproducto.getValueAt(i,4).toString()+","+jtproducto.getValueAt(i, 0)+","+info.getInt(1)+","+ lblfacturaid.getText());
       
                            
                        } 
                           
                            
                        }

    
    
    
    
    
    
    System.out.println("CREA EL ARCHIVO NO ENTRE TODAVIA");
    
    //PARTE DE ARCHIVOS PARA INSERTAR------------------------->
    archivo=new File("C:\\Documentos Empresa\\FACTURAS\\"+fecha.replace("/","-")+"\\FACTURA N°"+lblfacturaid.getText()+"-CLIENTE "+txtnombredelcliente.getText()+".txt");
    
    
    
    
    System.out.println(archivo.toString());
    System.out.println("CREE EL ARCHIVO");
           escribir=new FileWriter(archivo,true);
    
     ayudaescribir=new BufferedWriter(escribir);
     imprimi=new PrintWriter(ayudaescribir);
     System.out.println("CREACION BUFER");
                        //ayudaescribir.append("HOLA C:");
                       imprimi.println("FACTURA "+lblfacturaid.getText());
                        imprimi.println("FECHA "+lblfecha.getText());
                        imprimi.println("CLIENTE "+txtnombredelcliente.getText());
                        imprimi.println();
                        imprimi.println();
                        imprimi.print("ID\t");imprimi.print("SERI\t");
                        imprimi.print("NOMB\t");imprimi.print("V/UN\t ");
                        imprimi.print("CANT\t");imprimi.print("SUBT\t");
                        imprimi.println();imprimi.println();
                        for(int i=0;i<jtproducto.getRowCount();i++ ){
                           for(int j=0;j<jtproducto.getColumnCount()-1;j++ ){
                            imprimi.print(jtproducto.getValueAt(i, j).toString()+"\t");
                            
                            
                        } 
                         imprimi.println();   
                            
                        }
                        imprimi.println("---------------------------------------------");
                        imprimi.println("SUBTOTAL "+lblsubtotal.getText());
                        imprimi.println("IVA 16% "+lbliva.getText());
                        imprimi.println("TOTAL "+lbltotal.getText());
                   System.out.println("VOY A CERRAR EL ARCHIVO");
                    
                   
                   
                   imprimi.close();
                    ayudaescribir.close();
                   escribir.close();
                   
                    
                    
                   System.out.println("YA CERRE EL ARCHIVO");

                    JOptionPane.showMessageDialog(this,"FACTURA CREADA");
                    if(JOptionPane.showConfirmDialog(this, "Desea abrir la factura que acabo de generar")==0){
      File archivoabrir=new File("C:\\Documentos Empresa\\FACTURAS\\"+fecha.replace("/","-")+"\\FACTURA N°"+lblfacturaid.getText()+"-CLIENTE "+txtnombredelcliente.getText()+".txt");
      Desktop.getDesktop().open(archivoabrir);
      }
                    modelo.setNumRows(0);
                    txtidproducto.setText("");
                    txtnombredelcliente.setText("");
                    lblsubtotal.setText("");
                    lbliva.setText("");
                    lbltotal.setText("");
                    jscantidadproductos.setValue(0);
                     lblfacturaid.setText((Integer.parseInt(lblfacturaid.getText())+1)+"");
                    }catch(Exception e){
                             
                             }
















// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jscantidadproductos;
    private javax.swing.JTable jtproducto;
    private javax.swing.JLabel lblfacturaid;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblidempleado;
    private javax.swing.JLabel lbliva;
    private javax.swing.JLabel lblnombreempleado;
    private javax.swing.JLabel lblnombreproducto;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtnombredelcliente;
    // End of variables declaration//GEN-END:variables
}
