/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ConexionBasesdeDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JFPrincipalAdministrador extends javax.swing.JFrame {
ConexionBasesdeDatos conexion;
    /**
     * Creates new form JFPrincipalAdministrador
     */
    public JFPrincipalAdministrador(ConexionBasesdeDatos conexion,int idadmin) {
        initComponents();
        this.conexion=conexion;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DPEscritorio = new javax.swing.JDesktopPane();
        JPEscritorio = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DPEscritorio.setBackground(new java.awt.Color(0, 153, 153));
        DPEscritorio.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        JPEscritorio.setBackground(new java.awt.Color(0, 153, 153));
        JPEscritorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        JPEscritorio.setToolTipText("Bienvenido Administrador");

        javax.swing.GroupLayout JPEscritorioLayout = new javax.swing.GroupLayout(JPEscritorio);
        JPEscritorio.setLayout(JPEscritorioLayout);
        JPEscritorioLayout.setHorizontalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1648, Short.MAX_VALUE)
        );
        JPEscritorioLayout.setVerticalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        DPEscritorio.add(JPEscritorio);
        JPEscritorio.setBounds(0, 0, 1650, 900);

        menuBar.setBackground(java.awt.SystemColor.activeCaption);
        menuBar.setBorder(null);
        menuBar.setForeground(java.awt.SystemColor.activeCaption);
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        fileMenu.setBackground(java.awt.SystemColor.windowText);
        fileMenu.setBorder(null);
        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Apps-preferences-contact-list-icon.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Empleados");
        fileMenu.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-list-add-user-icon.png"))); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Añadir");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setBackground(java.awt.SystemColor.activeCaption);
        saveMenuItem.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-find-user-icon.png"))); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Consultar");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setBackground(java.awt.SystemColor.activeCaption);
        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Apps-utilities-file-archiver-icon.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Productos");
        editMenu.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N

        cutMenuItem.setBackground(java.awt.SystemColor.activeCaption);
        cutMenuItem.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document-add-icon.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Añadir o modificar");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        jMenuItem3.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sign-Refresh-icon.png"))); // NOI18N
        jMenuItem3.setText("Modificar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem3);

        menuBar.add(editMenu);

        helpMenu.setBackground(java.awt.SystemColor.activeCaption);
        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mimetypes-application-vnd-ms-excel-icon.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Reportes");
        helpMenu.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventory-maintenance-icon.png"))); // NOI18N
        jMenuItem1.setText("Inventarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Accounting-icon.png"))); // NOI18N
        jMenuItem2.setText("Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem2);

        menuBar.add(helpMenu);

        jMenu5.setBackground(java.awt.SystemColor.activeCaption);
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete-icon.png"))); // NOI18N
        jMenu5.setText("Salir");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        jMenuItem14.setText("Cerrar Sesion");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        menuBar.add(jMenu5);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DPEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DPEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

        JFPrincipalAdministradorEmpleadosAñadir ventana=new JFPrincipalAdministradorEmpleadosAñadir(conexion);
        DPEscritorio.add(ventana);
        ventana.show();
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
   JFPrincipalAdministradorEmpleadosConsultar ventana=new JFPrincipalAdministradorEmpleadosConsultar(conexion);
   DPEscritorio.add(ventana);
   ventana.show();
        

// TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
JFPrincipalAdministradorProductosAñadir ventana=new JFPrincipalAdministradorProductosAñadir(conexion);
DPEscritorio.add(ventana);
   ventana.show();
        

// TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    
JFPrincipalAdministradorReportesInventarioDiario ventana=new JFPrincipalAdministradorReportesInventarioDiario(conexion);
DPEscritorio.add(ventana);
   ventana.show();        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

JFPrincipalAdministradorReportesVentas   ventana=new JFPrincipalAdministradorReportesVentas(conexion);
DPEscritorio.add(ventana);
   ventana.show();              




// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
                
        if(JOptionPane.showConfirmDialog(this, "ESTA SEGURO DE CERRAR SESION")==0){
       JFcerrarSesionn ventana=new JFcerrarSesionn();
       ventana.show();
       this.dispose();
        }
 //JFcerrarsesion ventana=new JFcerrarsesion();
         // DPEscritorio.add(ventana);
         // ventana.show();         

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
JFPrincipalAdministradorProductosConsultar ventana=new JFPrincipalAdministradorProductosConsultar(conexion,0);
DPEscritorio.add(ventana);
   ventana.show(); 
        


// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DPEscritorio;
    private javax.swing.JPanel JPEscritorio;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
