/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ConexionBasesdeDatos;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JFPrincipalAdministradorEmpleadosConsultar extends javax.swing.JInternalFrame {
ConexionBasesdeDatos conexion;
    /**
     * Creates new form JFPrincipalAdministradorEmpleadosConsultar
     */
    public JFPrincipalAdministradorEmpleadosConsultar(ConexionBasesdeDatos conexion) {
        initComponents();
        this.conexion=conexion;
        this.closable=true;
        this.iconable=true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        DCFecha = new datechooser.beans.DateChooserCombo();
        txtapellido2 = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbmasculino = new javax.swing.JRadioButton();
        rbfemenino = new javax.swing.JRadioButton();
        btnaditar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();

        setTitle("Consultar Empleados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-find-user-icon.png"))); // NOI18N

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Digite codigo del empledo");

        txtid.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        btnconsultar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel10.setText("Fecha de Ingreso");

        try {
            DCFecha.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2014, 4, 10),
                new java.util.GregorianCalendar(2014, 4, 10))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    DCFecha.setEnabled(false);
    DCFecha.setFieldFont(new java.awt.Font("Century Gothic", java.awt.Font.PLAIN, 11));

    txtapellido2.setEditable(false);
    txtapellido2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

    txtapellido1.setEditable(false);
    txtapellido1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

    jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel3.setText("Apellidos");

    txtnombre.setEditable(false);
    txtnombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel2.setText("Nombre(s)");

    jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel9.setText("Cedula");

    txtcedula.setEditable(false);
    txtcedula.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

    jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel4.setText("Genero");

    rbmasculino.setBackground(java.awt.SystemColor.activeCaption);
    rbmasculino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    rbmasculino.setText("Masculino");
    rbmasculino.setEnabled(false);

    rbfemenino.setBackground(java.awt.SystemColor.activeCaption);
    rbfemenino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    rbfemenino.setText("Femenino");
    rbfemenino.setEnabled(false);
    rbfemenino.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbfemeninoActionPerformed(evt);
        }
    });

    btnaditar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    btnaditar.setText("Editar");
    btnaditar.setEnabled(false);
    btnaditar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnaditarActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
    jLabel11.setText("Clave");

    txtclave.setEditable(false);
    txtclave.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnconsultar)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbmasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbfemenino)
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtclave)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaditar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnconsultar))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10)
                .addComponent(DCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(rbmasculino)
                .addComponent(rbfemenino)
                .addComponent(jLabel11)
                .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnaditar)
            .addContainerGap(21, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemeninoActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
    
    try{
    if(conexion.consultarexistencia("PERSONA", "pers_nombre", "pers_id", txtid.getText())){
      ResultSet info=conexion.consultarconcondicion("PERSONA","pers_cedula,pers_nombre,pers_apellido1,pers_apellido2,pers_genero,pers_fecha,pers_clave", "pers_id="+txtid.getText());
      info.next();
      txtcedula.setText(info.getInt(1)+"");
      txtnombre.setText(info.getString(2));
      txtapellido1.setText(info.getString(3));
      txtapellido2.setText(info.getString(4));
        System.out.println("GENERO-->"+info.getString(5));
               
   
      if(info.getString(5).equals("M")){
              rbmasculino.setSelected(true);
  rbfemenino.setSelected(false);
      }
      else{
           if(info.getString(5).equals("F")){
              rbfemenino.setSelected(true);
rbmasculino.setSelected(false);
      }
         
      }
      String a[] =new String [3];
      a=info.getString(6).split("-");
      String fecha="";
      fecha=a[2]+"/"+a[1]+"/"+a[0];
        
      DCFecha.setText(fecha);
      txtclave.setText(info.getString(7));
      btnaditar.setEnabled(true);
    }
    else{
        JOptionPane.showMessageDialog(this, "El codigo no existe");
        txtid.setText("");
        txtnombre.setText("");
        txtapellido1.setText("");
        txtapellido2.setText("");
        txtcedula.setText("");
        txtclave.setText("");
       rbfemenino.setSelected(false);
       rbmasculino.setSelected(false);
       btnaditar.setEnabled(false);
    }
    
    
    }catch(Exception e){
        
    }
    
        



// TODO add your handling code here:
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnaditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaditarActionPerformed
      txtid.getText();
    txtnombre.getText();
    txtapellido1.getText();
    txtapellido2.getText();
    txtcedula.getText();
    rbmasculino.isSelected();
    rbfemenino.isSelected();
    DCFecha.getText();
    if(btnaditar.getText().equals("Guardar")){
      
    String genero="";
    if(rbmasculino.isSelected()){
        genero="M";
    }
    if(rbfemenino.isSelected()){
        genero="F";
    }
    try{
    conexion.actualizar("PERSONA", "pers_cedula = "+txtcedula.getText()+",pers_nombre = '"+txtnombre.getText()+"',pers_apellido1 = '"+txtapellido1.getText()+"',"+
           "pers_apellido2 = '"+txtapellido2.getText() +"',pers_genero = '"+genero+"'" , "pers_id", txtid.getText());
    JOptionPane.showMessageDialog(this, "Actualizacion exitosa");
    btnaditar.setText("Editar");
           btnconsultar.setEnabled(true);
txtid.setEditable(true);
       btnconsultar.setEnabled(true);
    
       txtnombre.setEditable(false);
    txtapellido1.setEditable(false);
    txtapellido2.setEditable(false);
    txtcedula.setEditable(false);
    txtclave.setEditable(false);
    rbmasculino.setEnabled(false);
    rbfemenino.setEnabled(false);
    DCFecha.setEnabled(false);
    }catch(Exception e){
         JOptionPane.showMessageDialog(this, "Error en la actualizacion ");
    }
    }else{
        btnaditar.setText("Guardar");
         txtid.setEditable(false);
       btnconsultar.setEnabled(false);
    
       txtnombre.setEditable(true);
    txtapellido1.setEditable(true);
    txtapellido2.setEditable(true);
    txtcedula.setEditable(true);
    txtclave.setEditable(true);
    rbmasculino.setEnabled(true);
    rbfemenino.setEnabled(true);
    DCFecha.setEnabled(true);
        
    }

// TODO add your handling code here:
    }//GEN-LAST:event_btnaditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DCFecha;
    private javax.swing.JButton btnaditar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtapellido2;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
